import type { Metadata } from "next";
import { Geist, Geist_Mono, Tajawal } from "next/font/google";
// import "../../../public-dashboard/assets/css/plugins.css";
import "../../../../public-dashboard/assets/css/table.css";
import "../../../../public-dashboard/assets/css/style.css";

// import "../../styles/dashboard/scss/style.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});
const arabicFont = Tajawal({
  variable: "--font-arabic",
  subsets: ["arabic"],
  display: "swap",
  weight: ["400", "700"], // Add the weights you want to use
});
export const metadata: Metadata = {
  title: "Ekomart-Grocery-Store(e-Commerce) HTML Template",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/assets/images/fav.png",
        type: "image/x-icon",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`dashboard-wrapper ${arabicFont.variable}`}>{children}</div>
  );
}
